### Register Admin
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "role": "ADMIN",
  "name": "Admin3",
  "surname": "",
  "email": "admin3@gmail.com",
  "phoneNumber": "+33062330317",
  "password": "Admin1234_"
}

### Login Admin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin3@gmail.com",
  "password": "Admin1234_"
}

### Get All Users (including deleted)
GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjJAdGVzdC5jb20iLCJpYXQiOjE3NzMyMjUzNzcsInVzZXJJZCI6MTEsInJvbGVzIjoiQURNSU4iLCJleHAiOjE3NzMyMjU2Nzd9.3UMAEA4Mb72sIdZKMtaZszCLob7ebxS5Gh4R_nkkJMM

### Soft Delete User
DELETE http://localhost:8080/api/v1/users/9
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTc3MjYyMjYxNSwidXNlcklkIjo5LCJyb2xlcyI6IkFETUlOIiwiZXhwIjoxNzcyNjIyOTE1fQ.oLuypiGHkdsMvfILl0UFnf_kCgBNoWjIMp-0-Wtuk1I

### Get Deleted Users
GET http://localhost:8080/api/v1/users/deleted
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjJAdGVzdC5jb20iLCJpYXQiOjE3NzI2MzQ4OTQsInVzZXJJZCI6MTEsInJvbGVzIjoiQURNSU4iLCJleHAiOjE3NzI2MzUxOTR9.9CJjAb7kYNFFp7M2duhn_nPui9kOGFiqSO3TAO2WI0g

### Restore User
PUT http://localhost:8080/api/v1/users/1/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjJAdGVzdC5jb20iLCJpYXQiOjE3NzI2MzIwMzMsInVzZXJJZCI6MTEsInJvbGVzIjoiQURNSU4iLCJleHAiOjE3NzI2MzIzMzN9.2I-W9pDRHlr-AnwM6ByJy_Omppql4IBD2g1DoOfPbT8

### Change User Role
PUT http://localhost:8080/api/v1/users/1/role?role=CLIENT
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjJAdGVzdC5jb20iLCJpYXQiOjE3NzI2MzMyMjgsInVzZXJJZCI6MTEsInJvbGVzIjoiQURNSU4iLCJleHAiOjE3NzI2MzM1Mjh9.jZqoUxH4ohkPFZzW28uiGjMH7EmZzH2wlbjlgJ9k6pI

### ADMIN DELETE BILL
DELETE http://localhost:8080/api/v1/bills/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjJAdGVzdC5jb20iLCJpYXQiOjE3NzI2MzIwMzMsInVzZXJJZCI6MTEsInJvbGVzIjoiQURNSU4iLCJleHAiOjE3NzI2MzIzMzN9.2I-W9pDRHlr-AnwM6ByJy_Omppql4IBD2g1DoOfPbT8

### ADMIN RESTORE BILL
PUT http://localhost:8080/api/v1/bills/11/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjJAdGVzdC5jb20iLCJpYXQiOjE3NzI2MzIwMzMsInVzZXJJZCI6MTEsInJvbGVzIjoiQURNSU4iLCJleHAiOjE3NzI2MzIzMzN9.2I-W9pDRHlr-AnwM6ByJy_Omppql4IBD2g1DoOfPbT8

### ADMIN GET ALL BILLS
GET http://localhost:8080/api/v1/bills
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjJAdGVzdC5jb20iLCJpYXQiOjE3NzI2MzIyODMsInVzZXJJZCI6MTEsInJvbGVzIjoiQURNSU4iLCJleHAiOjE3NzI2MzI1ODN9.atvwOk5YG4JinJYgeJaEz1xMDxaczkVAIW6RJI9-SgQ

### ADMIN EDIT USERS
PUT http://localhost:8080/api/v1/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjNAZ21haWwuY29tIiwiaWF0IjoxNzczNjU0MTg4LCJ1c2VySWQiOjEyLCJyb2xlcyI6IkFETUlOIiwiZXhwIjoxNzczNjU0NDg4fQ.TIi9QxsxZEw9kq7Yh6LhMMxzCGzx40UsCfA5AX3DtHc
Content-Type: application/json

{
  "name": "John",
  "surname": "Smith",
  "email": "johnsmith@email.com",
  "phoneNumber": "+37060000000",
  "role": "CLIENT",
  "primaryResidenceId": 12
}
### Create a new residence
POST http://localhost:8080/api/v1/residences
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjNAZ21haWwuY29tIiwiaWF0IjoxNzczNjUzODM3LCJ1c2VySWQiOjEyLCJyb2xlcyI6IkFETUlOIiwiZXhwIjoxNzczNjU0MTM3fQ.1z4j8iKpFZs2rlapQ7cvesfbxqqbMXBtfhnbTTx-FpM

{
  "streetAddress": "Compalist st. 9",
  "flatNumber": "167",
  "city": "Kyiv",
  "postalCode": "XD-10532",
  "country": "Ukraine",
  "residenceType": "FLAT",
  "isPrimary": false,
  "isSecondary": true,
  "active": true,
  "user": {
    "id": 5
  }
}

### Create USer (ADMIN)
POST http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjNAZ21haWwuY29tIiwiaWF0IjoxNzczNjU3NzE5LCJ1c2VySWQiOjEyLCJyb2xlcyI6IkFETUlOIiwiZXhwIjoxNzczNjU4MDE5fQ.sSC4pBV6rs1O4Zh7fYZztPQaN79w7MvGU6gXQr6JU1E
Content-Type: application/json

{
"role": "CLIENT",
"name": "John",
"surname": "Smithenko",
"email": "john@test.com",
"password": "John1234_",
"phoneNumber": "+37060000001"
}