@baseUrl = http://localhost:8080/api/v1

@admin_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjNAZ21haWwuY29tIiwiaWF0IjoxNzczNzYwMjU5LCJ1c2VySWQiOjEyLCJyb2xlcyI6IkFETUlOIiwiZXhwIjoxNzczNzYwNTU5fQ.FNFHTNpALpQXP9QhF-IF1KvkJb7tYroGkxHe5_znc_Y
@client_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzd2FwQGdtYWlsLmNvbSIsImlhdCI6MTc3Mzc2MDIwNCwidXNlcklkIjo2LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc3Mzc2MDUwNH0.fqIJDZWC68X7tO9GSXUz7XTJNTo7f6xNc2pWIPVV7uk

### Login Admin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin3@gmail.com",
  "password": "Admin1234_"
}

###Login CLIENT
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "swap@gmail.com",
  "password": "Swap1234_"
}

### GET ALL Payments (ADMIN)
GET {{baseUrl}}/payment
Authorization: Bearer {{admin_token}}

### Update Payment (ADMIN)
PUT {{baseUrl}}/payment/1
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "success": false,
  "provider": "Stripe",
  "timestamp": "2026-03-17T12:00:00"
}

### Pay the bill/Create Payment (CLIENT)
POST {{baseUrl}}/payment/pay
Content-Type: application/json
Authorization: Bearer {{client_token}}

{
  "billId": 7,
  "userId": 6,
  "amount": 18.98,
  "provider": "PAYPAL",
  "methodToken": "demo-mock-token-abc"
}