### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "role": "CLIENT",
  "surname": "1",
  "name": "test",
  "email": "fake1@gmail.com",
  "phoneNumber": "+370",
  "password": "123456"
}

###Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "fake1@gmail.com",
  "password": "123456"
}

### Create a new residence
POST http://localhost:8080/api/residences
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmYWtlMTJAZ21haWwuY29tIiwiaWF0IjoxNzUzMjY5MTE3LCJ1c2VySWQiOjIsInJvbGVzIjoiQ0xJRU5UIiwiZXhwIjoxNzUzMjY5NDE3fQ.O4VuN1PKueJ4dgC-twB54Fi-NXBo0WwGXoEhW4-BsH8

{
  "user": {
    "id": 2
  },
  "streetAddress": "1234 Main St",
  "flatNumber": "4B",
  "city": "Vilnius",
  "postalCode": "LT-01100",
  "country": "Lithuania",
  "residenceType": "FLAT",
  "isPrimary": true,
  "active": true
}