### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "role": "CLIENT",
  "surname": "T",
  "name": "Hlib",
  "email": "emptyno@gmail.com",
  "phoneNumber": "+3701",
  "password": "123456",
  "residenceRequest": {
    "streetAddress": "Gedimino pr. 9",
    "flatNumber": "19",
    "city": "Vilnius",
    "postalCode": "LT-01103",
    "country": "Lithuania",
    "residenceType": "FLAT",
    "isPrimary": true
  }
}

### Register Company
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "role": "COMPANY",
  "name": "DTEK",
  "email": "dtek@gmail.com",
  "phoneNumber": "+37012345678",
  "password": "Qwerty12345!"
}

###Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "12345678Ab_"
}

###Get my residences
GET http://localhost:8080/api/v1/residences
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbXB0eW5vQGdtYWlsLmNvbSIsImlhdCI6MTc1MzI3NTU1MywidXNlcklkIjo0LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc1MzI3NTg1M30.rj_yPdCtPLbfI8NG5sHfb1wckLbX8fcYD0gGCcz4iMg

###Login COMPANY
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "dtek1@gmail.com",
  "password": "Dtek1234_"
}


###Login CLIENT
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "swap@gmail.com",
  "password": "Swap1234_"
}



### Create a new residence
POST http://localhost:8080/api/v1/residences
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdGVrMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI2MzI4NzEsInVzZXJJZCI6Nywicm9sZXMiOiJDT01QQU5ZIiwiZXhwIjoxNzcyNjMzMTcxfQ.yrZcimcsMQQsN5cyuovZM3vAT0g3yB412gaHzHi-FIs

{
  "streetAddress": "Ulvidino g. 87",
  "flatNumber": "23",
  "city": "Vilnius",
  "postalCode": "LT-01107",
  "country": "Lithuania",
  "residenceType": "FLAT",
  "isPrimary": true
}
### CLIENT Get all res
GET http://localhost:8080/api/v1/residences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzd2FwQGdtYWlsLmNvbSIsImlhdCI6MTc3MjYzMjk1MiwidXNlcklkIjo2LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc3MjYzMzI1Mn0.PIJK4eu3hOV_Nh6BUDoH7W6RlxxGgWGDV-PHlesz738

### Create a new residence
POST http://localhost:8080/api/v1/residences
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbXB0eW5vQGdtYWlsLmNvbSIsImlhdCI6MTc1MzM0MTUzNiwidXNlcklkIjo0LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc1MzM0MTgzNn0.rOV2Ar8jkHPARybTqCIAna56CVMtbWn9x4ZYnoqNNJc

{
  "streetAddress": "Antakalnio g. 19",
  "flatNumber": "",
  "city": "Vilnius",
  "postalCode": "LT-10232",
  "country": "Lithuania",
  "residenceType": "HOUSE",
  "isPrimary": false,
  "isSecondary": true,
  "active": true,
  "user": {
    "id": 2
  }
}

### Create a new bill
POST http://localhost:8080/api/v1/bills/residence/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdGVrMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI2MzE0MzIsInVzZXJJZCI6Nywicm9sZXMiOiJDT01QQU5ZIiwiZXhwIjoxNzcyNjMxNzMyfQ.Wr0-ynQ0vT9I0BjwhqLfGBTSnxj7ochxbDSzi22wL2o


{
  "name": "DTEK bill for 01.26",
  "amount": 145.66,
  "dueDate": "2026-03-30",
  "type": "ELECTRICITY",
  "status": "OPEN"
}

### COMPANY DELETE OWN BILL
DELETE http://localhost:8080/api/v1/bills/11
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdGVrMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI2MzE2NTUsInVzZXJJZCI6Nywicm9sZXMiOiJDT01QQU5ZIiwiZXhwIjoxNzcyNjMxOTU1fQ.tjwgIJU5Zuv4gXEXlSxKWH84v-25Sy8YUMT-8aatlks

### CLIENT DELETE BILL (FORBIDDEN)
DELETE http://localhost:8080/api/v1/bills/11
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzd2FwQGdtYWlsLmNvbSIsImlhdCI6MTc3MjYzMjE5NCwidXNlcklkIjo2LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc3MjYzMjQ5NH0.Qjusc52yh7CyrlR4DsKAsOw3Pc5zgD1vJ-zhx7KdCek

### CLIENT GET MY BILLS
GET http://localhost:8080/api/v1/bills/my
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzd2FwQGdtYWlsLmNvbSIsImlhdCI6MTc3MjYzMjM4NiwidXNlcklkIjo2LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc3MjYzMjY4Nn0.oNa41ozlcEC07RTozLDUAjum6YuiajfAgijB1Ylu9Oo


### Pay the bill
POST http://localhost:8080/api/v1/payment/pay
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzd2FwQGdtYWlsLmNvbSIsImlhdCI6MTc3MjYzNjM0OSwidXNlcklkIjo2LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc3MjYzNjY0OX0.rHdevc6VF8L6u1RUoaOvy93gezFGK6NPwiZr_UtZd8M

{
  "billId": 3,
  "amount": 18.59,
  "provider": "PAYPAL",
  "methodToken": "demo-mock-token-abc",
  "userId": 1
}
### Pay the bill 2
POST http://localhost:8080/api/v1/bills/3/pay?amount=145.66&provider=PAYPAL&methodToken=test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzd2FwQGdtYWlsLmNvbSIsImlhdCI6MTc3MjYzMzg4MSwidXNlcklkIjo2LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc3MjYzNDE4MX0.v2cXbHr_EtszzCCGN1JmFJo7TlLg9NEcssZlJ-SqgbY

### Check bill status

GET http://localhost:8080/api/v1/bills/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdGVrQGdtYWlsLmNvbSIsImlhdCI6MTc1MzI2MjI2NywiZXhwIjoxNzUzMjYyNTY3fQ.Px8BGMM5zJKMyGLSLqoi4JPg82fWWVVYFttT0Aoujj4

### Set Primary residence
PUT http://localhost:8080/api/v1/residences/1/set-primary
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbXB0eW5vQGdtYWlsLmNvbSIsImlhdCI6MTc1MzM0OTM4OSwidXNlcklkIjo0LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc1MzM0OTY4OX0.u5-hlA5m9fq_f0jUT7XtBL-hBqduY-HqskDBG-kyNTY

### Check something
GET http://localhost:8080/api/bills/17
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdGVrQGdtYWlsLmNvbSIsImlhdCI6MTc1MzI5NjUxMywidXNlcklkIjozLCJyb2xlcyI6IkNPTVBBTlkiLCJleHAiOjE3NTMyOTY4MTN9.k7VBNJbFteMK9EeA-diMOUC7DRwNXwGVM_u89zdqiD0

