### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "role": "CLIENT",
  "surname": "1",
  "name": "test",
  "email": "fake1@gmail.com",
  "phoneNumber": "+370",
  "password": "123456"
}

###Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "fake1@gmail.com",
  "password": "123456"
}

### Create a new residence
POST http://localhost:8080/api/residences
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmYWtlMUBnbWFpbC5jb20iLCJpYXQiOjE3NTI3NzgzNjMsImV4cCI6MTc2MTQxODM2M30.NKb66I4V_4Xp5Mgw6AJ5rA-WZKQHz_Qmp7LOz0d8SSA

{
  "user": {
    "id": 1
  },
  "streetAddress": "123 Main St",
  "flatNumber": "4B",
  "city": "Vilnius",
  "postalCode": "LT-01100",
  "country": "Lithuania",
  "residenceType": "flat",
  "isPrimary": true,
  "active": true
}