@baseUrl = http://localhost:8080/api/v1

@admin_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjNAZ21haWwuY29tIiwiaWF0IjoxNzczNzQ3MTcyLCJ1c2VySWQiOjEyLCJyb2xlcyI6IkFETUlOIiwiZXhwIjoxNzczNzQ3NDcyfQ.fkNn00Qidg7lbg_AIXh-BhHqnwMgIcfoEXzCehJ5JC0
@client_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzd2FwQGdtYWlsLmNvbSIsImlhdCI6MTc3Mzc0MjI4NiwidXNlcklkIjo2LCJyb2xlcyI6IkNMSUVOVCIsImV4cCI6MTc3Mzc0MjU4Nn0.N06KdYs9cMte0XT5zCaZg8XFCs-e2nKCiOWb_N-LM4Y
@company_token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdGVrMUBnbWFpbC5jb20iLCJpYXQiOjE3NzM3NDI1NzEsInVzZXJJZCI6Nywicm9sZXMiOiJDT01QQU5ZIiwiZXhwIjoxNzczNzQyODcxfQ.e-oBQlr2h-iWU4d1H5bNhRmPGXd6cXrwhy8euYLsYp0


### Login Admin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin3@gmail.com",
  "password": "Admin1234_"
}

###Login CLIENT
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "swap@gmail.com",
  "password": "Swap1234_"
}

###Login COMPANY
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "dtek1@gmail.com",
  "password": "Dtek1234_"
}

### CLIENT CREATE RESIDENCE
POST {{baseUrl}}/residences
Authorization: Bearer {{client_token}}
Content-Type: application/json

{
  "streetAddress": "Main Street 10",
  "flatNumber": "5A",
  "city": "Warsaw",
  "postalCode": "00-001",
  "country": "Poland",
  "residenceType": "FLAT",
  "isPrimary": true
}

### ADMIN CREATE RESIDENCE
POST {{baseUrl}}/residences/admin
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "userId": 1,
  "streetAddress": "Admin Created Street 20",
  "flatNumber": "2B",
  "city": "Krakow",
  "postalCode": "30-002",
  "country": "Poland",
  "residenceType": "HOUSE",
  "isPrimary": false
}

### CLIENT GET MY RESIDENCES
GET {{baseUrl}}/residences
Authorization: Bearer {{client_token}}

### ADMIN GET USER RESIDENCES
GET {{baseUrl}}/users/6/residences
Authorization: Bearer {{admin_token}}

### COMPANY DASHBOARD (ALL)
GET {{baseUrl}}/residences/company/dashboard
Authorization: Bearer {{company_token}}

### COMPANY SEARCH RESIDENCES
GET {{baseUrl}}/residences/company/dashboard?street=Gedimino
Authorization: Bearer {{company_token}}

### UPDATE RESIDENCE
PUT {{baseUrl}}/residences/15
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "streetAddress": "Updated Street 67",
  "city": "New York",
  "postalCode": "80-001",
  "country": "USA",
  "residenceType": "HOUSE",
  "isPrimary": true,
  "isActive": true
}

### SET PRIMARY RESIDENCE
PUT {{baseUrl}}/residences/14/set-primary
Authorization: Bearer {{client_token}}

### DEACTIVATE RESIDENCE
PUT {{baseUrl}}/residences/15/deactivate
Authorization: Bearer {{client_token}}

### ACTIVATE RESIDENCE
PUT {{baseUrl}}/residences/14/activate
Authorization: Bearer {{client_token}}

### ADMIN DELETE RESIDENCE
DELETE {{baseUrl}}/residences/15
Authorization: Bearer {{admin_token}}

### ADMIN RESTORE RESIDENCE
PUT {{baseUrl}}/residences/15/restore
Authorization: Bearer {{admin_token}}