spring.datasource.url=jdbc:postgresql://localhost:5173/billup
spring.datasource.username=postgres
spring.datasource.password=swap0196
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
auth.jwt.secret.key=${JWT_SECRET}
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.com.example.BillUp.services.PaymentService=INFO


auth.jwt.expiration-ms=3600000
auth.jwt.refresh-expiration-ms=604800000
